import Order from '../models/order';

const ORDERS = [
  new Order(
    'o1',
    '2020-04-03',
    'ärende',
    'Jag behöver en matkasse',
    'Inom två dagar',
    '0702415623',
    'Malin',
    'Knutsson',
    'malin.knutsson@gmail.com',
    'Näs 21',
    '',
    'ny'
  ),
  new Order(
    'o2',
    '2020-04-10',
    'ärende',
    'Jag har brutit benet och kan inte städa',
    'Så snart som möjligt',
    '0722849220',
    'Per',
    'Larsson',
    'per.larsson@gmail.com',
    'Näs 8',
    '',
    'ny'
  ),
  new Order(
    'o3',
    '2020-04-08',
    'ärende',
    'Jag behöver ett lass bönor och tomatburkar',
    'Så snart som möjligt',
    '0724553215',
    'Mikael',
    'Månsson',
    'mikael.mansson@gmail.com',
    'Näs 16',
    'Egnahemsfabriken',
    'aktiv'
  ),
  new Order(
    'o4',
    '2020-04-01',
    'ärende',
    'Jag behöver ett lass bönor och tomatburkar',
    'Så snart som möjligt',
    '0724553215',
    'Mikael',
    'Månsson',
    'mikael.mansson@gmail.com',
    'Näs 16',
    'Svenska Kyrkan Tjörn',
    'aktiv'
  ),
  new Order(
    'o5',
    '2020-04-02',
    'ärende',
    'Jag behöver ett lass bönor och tomatburkar',
    'Så snart som möjligt',
    '0724553215',
    'Mikael',
    'Månsson',
    'mikael.mansson@gmail.com',
    'Näs 16',
    'Egnahemsfabriken',
    'aktiv'
  ),
  new Order(
    'o6',
    '2020-04-05',
    'ärende',
    'Jag behöver ett lass bönor och tomatburkar',
    'Så snart som möjligt',
    '0724553215',
    'Molly',
    'Månsson',
    'molly.mansson@gmail.com',
    'Näs 16',
    'Egnahemsfabriken',
    'aktiv'
  ),
  new Order(
    'o7',
    '2020-04-05',
    'ärende',
    'Jag behöver ett lass tomatburkar',
    'Så snart som möjligt',
    '0724553215',
    'Molly',
    'Månsson',
    'molly.mansson@gmail.com',
    'Näs 16',
    'Egnahemsfabriken',
    'klar'
  ),
  new Order(
    'o8',
    '2020-04-05',
    'ärende',
    'Jag behöver ett lass toapapper',
    'Så snart som möjligt',
    '0724553215',
    'Molly',
    'Månsson',
    'molly.mansson@gmail.com',
    'Näs 16',
    'Egnahemsfabriken',
    'klar'
  ),
  new Order(
    'o9',
    '2020-04-05',
    'ärende',
    'Jag behöver mediciner från apoteket i Stenungsund',
    'Inom två dagar',
    '0702451563',
    'Anna',
    'Smith',
    'molly.mansson@gmail.com',
    'Näs 16',
    'Egnahemsfabriken',
    'klar'
  ),
  new Order(
    'o10',
    '2020-04-05',
    'ärende',
    'Jag behöver ett lass bönor och tomatburkar',
    'Så snart som möjligt',
    '0724553215',
    'Molly',
    'Månsson',
    'molly.mansson@gmail.com',
    'Näs 16',
    'Egnahemsfabriken',
    'klar'
  ),
  new Order(
    'o11',
    '2020-04-02',
    'ärende',
    'Jag behöver ett lass bönor och tomatburkar',
    'Så snart som möjligt',
    '0724553215',
    'Molly',
    'Månsson',
    'molly.mansson@gmail.com',
    'Näs 16',
    '',
    'inaktiv'
  )
];

export default ORDERS;
